### ISSUE TITLE
[dev.icinga.com #10800] Different database schemas required for Icinga2 and Ido

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga-core#1567]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10800

**Created by rafaelo on 2015-12-09 10:10:42 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-12-09 10:16:43 +00:00 (in Redmine)_

    Icinga Version: 2.4.1
    OS Version: rhel7

---

Hi,
I run Icinga2 on Centos 7.
Versions are icinga2-2.4.1-1.el7.centos.x86\_64.rpm and icinga-idoutils-1.13.3-0.el7.centos.x86\_64.rpm.
Icinga requires the Ido database version 1.14, but Idoutils require version 1.13.

Snippets from the syslog:

Icinga2 against a 1.13 database
icinga2\[1248\]: \[2015-12-09 11:03:26 +0100\] critical/IdoPgsqlConnection: Schema version '1.13.0' does not match the required version '1.14.0' (or newer)!

Ido2DB against a 1.14 database
ido2db\[32065\]: Error: DB Version 1.14.0 does not match needed schema version 1.13.0. Please check the upgrade docs!

There's something wrong with the packages.

Regards,
Ralf

**Comment by dnsmichi** [comment]
We won't put any effort into keeping the schema the same anymore. The idea was nice, but turns out that the schema itself doesn't allow for much changes (except for breaking 1.x compatibility). It is also hard to migrate an existing history into the new world. Migration allows for renaming your objects, and that's what many people do.
That's why there's no new 1.14.0 schema version since none of the recent 2.x improve the 1.x functionality. If there's a critical bug in the 1.x schema we may fix that independent from 2.x in the future.
